# 系统配置
System:
  AppName: 'fastfiber-demo' # 应用名称
  Port: 3000 # 启动端口
  LogResponseBody: false # 是否打印response日志，默认关闭，开启比较影响性能和存储，比如返回给前端数据很大时，记录日志消耗会比较大
  LogTimeFormat: 'Unix' #日志时间格式默认Unix time 如:1634610522，为空则为带时区的时间如2021-10-19T10:25:11+08:00，建议不要改默认配置，时间戳性能更好
  LogBufferSize: 1000 # 日志缓冲池，写日志瞬时并发超过1000时，会丢弃部分日志，按需可以适当调高

# 数据库配置
Database:
  IsInit: true # 是否初始化到fastfiber对象上
  Type: 'mysql' # 仅支持mysql 和 postgre
  SlowThreshold: 100 # 慢日志，单位毫秒，执行时间大于SlowThreshold的sql会被记录到日志中
  MaxIdleConns: 10 # 最大空闲连接数即一直持有
  MaxIdleTime: 1800 # 默认30分钟，最大空闲时间秒
  MaxLifeTime: 3600 # 默认1小时，配置时建议小于wait_timeout
  MaxOpenConns: 128 # 连接池大小
  EnableReplicas: false # 是否开启读写分离
  Dsn:
    Write: 'root:123456@tcp(127.0.0.1:3306)/dev?charset=utf8mb4&parseTime=True&loc=Local' # mysql
    # Write: 'host=127.0.0.1 port=5432 dbname=dev user=root password=123456 sslmode=disable TimeZone=Asia/Shanghai' # postgre
    Read:
      - 'root:123456@tcp(127.0.0.2:3306)/dev?charset=utf8mb4&parseTime=True&loc=Local'
      - 'root:123456@tcp(127.0.0.3:3306)/dev?charset=utf8mb4&parseTime=True&loc=Local'

# redis 配置
Redis:
  IsInit: true # 是否初始化到fastfiber对象上
  Addr: '127.0.0.1:6379'
  Password: ''
  MaxIdle: 10 #最大空闲连接数
  MaxActive: 1000 # 连接池大小
  IdleTimeout: 60 #空闲超时时间
  IndexDb: 0 #数据库

# Id生成器
IdWorker:
  IsInit: true # 是否初始化到全局对象
  WorkerId: 0 # 为0 则使用默认值 建议按照节点数量自行设置
  DataCenterId: 0 # 为0 则使用默认值 建议按照业务线自行设置
  Twepoch: 0 # 为0 则使用默认值

# 限流配置
Limiter:
  Enable: true # true开启 false 关闭
  IpWhiteList: # 白名单
    - '127.0.0.1'
    - '172.16.129.128'
    - '172.16.128.45'
    - '172.16.128.50'
    - '172.16.128.54'
    - '172.16.129.165'
    - '172.16.129.166'

# 接口缓存配置
ApiCache:
  Enable: false #true开启 false 关闭

# Tracing
Tracer:
  Enable: false
  HostPort: 127.0.0.1:6831 # jaeger server
